lua/lambdaplayers/lambda/weapons/hl2_ar2.lua
lua/lambdaplayers/lambda/weapons/hl2_crossbow.lua
lua/lambdaplayers/lambda/weapons/hl2_shotgun.lua
lua/lambdaplayers/lambda/weapons/hl2_smg1.lua

- Added secondary fire for AR2;
- Improved crossbow bolt damage check
- Made use of soundscript names for sounds instead of full directories

Changes to AR2, SMG, Shotgun, and Crossbow

---

lua/lambdaplayers/lambda/weapons/css_knife.lua
lua/lambdaplayers/lambda/weapons/fists.lua
lua/lambdaplayers/lambda/weapons/hl2_grenade.lua
lua/lambdaplayers/lambda/weapons/hl2_rpg.lua
lua/lambdaplayers/lambda/weapons/hl2_shotgun.lua
lua/lambdaplayers/lambda/weapons/misc_meathook.lua
lua/lambdaplayers/lambda/weapons/misc_paig.lua
lua/lambdaplayers/lambda/weapons/misc_shovel.lua
lua/lambdaplayers/lambda/weapons/misc_zombieclaws.lua

PAIG is missing the original SentryBuster mode and the Lambdas aren't afraid of it. _Yet._

Various fixes and clean up of weapons | Added Knife firstswing | PAIG and Fist

---

lua/lambdaplayers/autorun_includes/shared/lambda_toolguntools.lua
lua/lambdaplayers/lambda/sv_weaponhandling.lua

Oh also modified the emitter angle to be more accurate, I hope.

Physical Properties Tool | Make use of the muzzleflash ang and pos

---

lua/effects/gravitygunbeam.lua
lua/effects/gravitygunblast.lua
lua/lambdaplayers/lambda/weapons/gravitygun.lua
lua/lambdaplayers/lambda/weapons/hl2_crowbar.lua
lua/lambdaplayers/lambda/weapons/hl2_smg1.lua
lua/lambdaplayers/lambda/weapons/hl2_stunstick.lua
materials/sprites/physcannon_beam.vmt
materials/sprites/physcannon_blast.vmt

It came a bit banged up in the mail and is stuck in punting mode.
A bit rough and needs some love but it does the job.
Some changes to HL2 melee distance as Lambdas had less reach than players.

Zero Point Energy Field Manipulator 

---

lua/lambdaplayers/autorun_includes/shared/lambda_toolguntools.lua

Except the rope.
This should prevent some unforeseen consequences.

More tool checks to prevent placing things that shouldn't be placed on certain things

---

lua/entities/npc_lambdaplayer.lua
lua/lambdaplayers/autorun_includes/server/globals.lua
lua/lambdaplayers/autorun_includes/shared/convars.lua
lua/lambdaplayers/lambda/sv_locomotion.lua

Too much performance concerns that have been found during my testing
- Crashing typically happens when entering water
- Major performance drops typically happening whilst in water
For now this will be reverted

Revert Swimming

---

lua/lambdaplayers/lambda/weapons/hl2_slam.lua

While equipped and idle Lambda Players will randomly throw them around the map.

Added HL2 S.L.A.M.

---

lua/lambdaplayers/lambda/sv_states.lua

Fixed act animations starting and ending with T-Pose

---

lua/lambdaplayers/autorun_includes/shared/lambda_toolguntools.lua

Fix Typo in Ballsocket

---

lua/entities/npc_lambdaplayer.lua
lua/lambdaplayers/autorun_includes/client/netmessages.lua
lua/lambdaplayers/autorun_includes/server/building_entitycreation.lua
lua/lambdaplayers/autorun_includes/server/building_npccreation.lua
lua/lambdaplayers/autorun_includes/server/netmessages.lua
lua/lambdaplayers/autorun_includes/shared/convars.lua
lua/lambdaplayers/autorun_includes/shared/d_consolecommands.lua
lua/lambdaplayers/autorun_includes/shared/gamemode_overrides.lua
lua/lambdaplayers/autorun_includes/shared/lambda_toolguntools.lua
lua/lambdaplayers/lambda/sh_hooks.lua
lua/lambdaplayers/lambda/sh_util.lua
lua/lambdaplayers/lambda/sv_weaponhandling.lua
lua/lambdaplayers/lambda/weapons/gravitygun.lua
lua/lambdaplayers/lambda/weapons/holster.lua

I don't like those operator aliases.

Capitalization | && to and | || to or | The Weld Tool

---

lua/lambdaplayers/lambda/weapons/misc_medkit.lua

Lambdas holding it will always heal themselves if hurt or someone else hurt if they're not as aggressive.

Added Medkit

---

lua/lambdaplayers/autorun_includes/server/globals.lua
lua/lambdaplayers/autorun_includes/shared/d_consolecommands.lua
lua/lambdaplayers/lambda/panels/namepanel.lua

Apparently these enumerations don't exist on serverside.

Converted all NOTIFY_* enumerations to numbers

---

lua/entities/npc_lambdaplayer.lua
lua/lambdaplayers/autorun_includes/server/globals.lua
lua/lambdaplayers/autorun_includes/shared/convars.lua
lua/lambdaplayers/autorun_includes/shared/hooks.lua
lua/lambdaplayers/lambda/sh_hooks.lua
lua/lambdaplayers/lambda/sh_util.lua
lua/lambdaplayers/lambda/sh_x_metarecreations.lua

- Added an armor system for Lambda Players. Currently the only way for them to acquire it is by armor batteries.
- Added an item pickup system. External addons can add their entity to the pickup list with `LambdaPlayers_AddItemPickup( class, func )` function.
- Added option to display armor of Lambda Player when looking at it.

Added Armor & Item Pickup System

---

lua/lambdaplayers/lambda/sv_states.lua
lua/lambdaplayers/lambda/sv_weaponhandling.lua
lua/lambdaplayers/lambda/sv_x_universalactions.lua
lua/lambdaplayers/lambda/weapons/hl2_gravitygun.lua
lua/lambdaplayers/lambda/weapons/medkit.lua

Also a small check so if shelleffect = "none" it stop trying to create effects with an effect that doesn't exist.

Medkit/GG changed origin | Button pressing

---

lua/lambdaplayers/autorun_includes/shared/gamemode_overrides.lua
lua/lambdaplayers/lambda/weapons/misc_pan.lua

It just changes the tabulation in gamemode_overrides.

Tabulation fix

---

lua/lambdaplayers/lambda/weapons/hl2_rpg.lua

Use the damage flag for the RPG rocket instead of util.blastdamage.

Minor change to RPG damage

---

lua/lambdaplayers/lambda/weapons/physicsgun.lua

I forgot IsDisabled was a thing the first time I wanted to fix the physgun :)

Use IsDisabled for physgun ai check

---

lua/lambdaplayers/autorun_includes/shared/filesystem.lua

I don't know if you plan on making it a ConVar but eh.

Fix text chat not using custom made lines

---

lua/lambdaplayers/lambda/weapons/fists.lua
lua/lambdaplayers/lambda/weapons/hl2_gravitygun.lua
lua/lambdaplayers/lambda/weapons/hl2_grenade.lua
lua/lambdaplayers/lambda/weapons/hl2_shotgun.lua
lua/lambdaplayers/lambda/weapons/hl2_smg1.lua
lua/lambdaplayers/lambda/weapons/l4d2_golfclub.lua
lua/lambdaplayers/lambda/weapons/misc_katana.lua
lua/lambdaplayers/lambda/weapons/misc_paig.lua

Changes the weapons GetRangeSquaredTo with the IsInRange function.

Replace GetRangeSquaredTo with the IsInRange function in weapons

---

lua/lambdaplayers/autorun_includes/shared/d_registervoicetypes.lua

Otherwise they don't go looking for their own custom lines related to the voicetype if they have any.

Refresh VoiceProfiles

---

lua/entities/npc_lambdaplayer.lua
lua/lambdaplayers/autorun_includes/client/netmessages.lua
lua/lambdaplayers/autorun_includes/shared/a_hookhandling.lua
lua/lambdaplayers/autorun_includes/shared/convars.lua
lua/lambdaplayers/autorun_includes/shared/lambda_personalityfuncs.lua
lua/lambdaplayers/lambda/sh_util.lua
lua/lambdaplayers/lambda/sv_states.lua
lua/lambdaplayers/lambda/sv_weaponhandling.lua
lua/lambdaplayers/lambda/weapons/holster.lua
lua/lambdaplayers/lambda/weapons/misc_paig.lua

- `OnReload` weapon setting function will prevent weapon from reloading if it returns true;
- Reordered the retreat state's code to make movement canceling work properly;
- Fixed 'Use Panic Animations' setting not being used in the code;
- Fixed spawn armor value not being applied when Lambda respawns;
- `LambdaRunHook()` function will stop its `for ... do` loop if any of the `a,b,c,d,e,f` variables are valid.

Bugfixes & One Small Addition

---

lua/autorun/lambdaplayers-autorun.lua
lua/entities/npc_lambdaplayer.lua
lua/lambdaplayers/autorun_includes/client/netmessages.lua
lua/lambdaplayers/autorun_includes/server/globals.lua
lua/lambdaplayers/autorun_includes/server/netmessages.lua
lua/lambdaplayers/autorun_includes/shared/d_consolecommands.lua
lua/lambdaplayers/autorun_includes/shared/filesystem.lua
lua/lambdaplayers/autorun_includes/shared/hooks.lua
lua/lambdaplayers/autorun_includes/shared/mws.lua
lua/lambdaplayers/autorun_includes/shared/z_panels.lua
lua/lambdaplayers/lambda/panels/entitypanel.lua
lua/lambdaplayers/lambda/panels/modelspecificvp.lua
lua/lambdaplayers/lambda/panels/namepanel.lua
lua/lambdaplayers/lambda/panels/npcpanel.lua
lua/lambdaplayers/lambda/panels/playermodelblock.lua
lua/lambdaplayers/lambda/panels/profilepanel.lua
lua/lambdaplayers/lambda/panels/proppanel.lua
lua/lambdaplayers/lambda/panels/textpanel.lua
lua/lambdaplayers/lambda/sh_hooks.lua
lua/lambdaplayers/lambda/sh_util.lua
lua/lambdaplayers/lambda/sh_x_metarecreations.lua
lua/lambdaplayers/lambda/sv_locomotion.lua
lua/lambdaplayers/lambda/sv_weaponhandling.lua
lua/lambdaplayers/lambda/weapons/holster.lua

This should address the issues where Lambdas would try to go to an inaccessible, out-of-reach, and not connected areas.

Added ENT:IsAreaTraversable(), a replacement to CLuaLocomotion:IsAreaTraversable()

---

lua/lambdaplayers/autorun_includes/shared/mws.lua

Adds a Trace hull check to MWS to prevent lambdas from getting stuck on world geometry when spawned.

Added a TR check for MWS, plus little spawn effect
